# This is a basic workflow to help you get started with Actions

name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:
permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout rehius/usk
        uses: actions/checkout@v3
        with:
          repository: rehius/usk
          path: usk
      
      - name: Checkout rehius/busk
        uses: actions/checkout@v3
        with:
          repository: rehius/busk
          path: busk

      - name: Checkout raspberrypi/pico-sdk
        uses: actions/checkout@v3
        with:
          repository: raspberrypi/pico-sdk
          path: pico-sdk
          submodules: recursive

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y gcc-arm-none-eabi libnewlib-arm-none-eabi build-essential
  
      - name: Set PICO_SDK_PATH
        run: |
          echo "PICO_SDK_PATH=$GITHUB_WORKSPACE/pico-sdk" >> $GITHUB_ENV

      - name: Create symbolic link to pico_sdk_import.cmake
        run: |
          ln -s $PICO_SDK_PATH/external/pico_sdk_import.cmake $GITHUB_WORKSPACE/usk/pico_sdk_import.cmake
          ln -s $PICO_SDK_PATH/external/pico_sdk_import.cmake $GITHUB_WORKSPACE/busk/pico_sdk_import.cmake

      - name: Create symbolic link of some usk headers in busk
        run: |
          ln -s $GITHUB_WORKSPACE/usk/pins.h $GITHUB_WORKSPACE/busk/pins.h

      - name: Create 'generated' directory in usk source directory
        run: mkdir -p $GITHUB_WORKSPACE/usk/generated

      - name: Build busk
        run: | 
          mkdir -p $GITHUB_WORKSPACE/build/busk
          cd $GITHUB_WORKSPACE/build/busk
          cmake $GITHUB_WORKSPACE/busk
          make
          cd $GITHUB_WORKSPACE
      
      - name: Build usk
        run: | 
          mkdir -p $GITHUB_WORKSPACE/build/usk
          cd $GITHUB_WORKSPACE/build/usk
          cmake $GITHUB_WORKSPACE/usk
          make
          python3 $GITHUB_WORKSPACE/usk/prepare.py
          cd $GITHUB_WORKSPACE
  
      - name: Generate release tag
        id: tag
        run: |
          echo "release_tag=PicoFly_$(date +"%Y.%m.%d_%H-%M")" >> $GITHUB_OUTPUT

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.tag.outputs.release_tag }}
          files: |
            build/usk/firmware.uf2
            build/usk/update.bin
  

          