# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      
      - name: Checkout rehius/usk
        uses: actions/checkout@v3
        with:
          repository: rehius/usk
          path: usk
      
      - name: Checkout rehius/busk
        uses: actions/checkout@v3
        with:
          repository: rehius/busk
          path: busk

      - name: Checkout raspberrypi/pico-sdk
        uses: actions/checkout@v3
        with:
          repository: raspberrypi/pico-sdk
          path: pico-sdk
          submodules: recursive

      - name: Set PICO_SDK_PATH
        run: |
          echo "PICO_SDK_PATH=$GITHUB_WORKSPACE/pico-sdk" >> $GITHUB_ENV

      - name: Create symbolic link to pico_sdk_import.cmake
        run: |
          ln -s $PICO_SDK_PATH/external/pico_sdk_import.cmake $GITHUB_WORKSPACE/usk/pico_sdk_import.cmake
          ln -s $PICO_SDK_PATH/external/pico_sdk_import.cmake $GITHUB_WORKSPACE/busk/pico_sdk_import.cmake

      - name: Create 'generated' directory for usk
        run: mkdir -p $GITHUB_WORKSPACE/usk/generated

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y gcc-arm-none-eabi libnewlib-arm-none-eabi build-essential

      - name: Build usk
        run: | 
          mkdir build_usk
          cd ./build_usk
          cmake $GITHUB_WORKSPACE/usk
          make

          