name: Build binaries

on:
  push:
    branches: [main]

  pull_request:
    branches: [main]

jobs:
  build-binaries:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform:
        - name: linux
          task: build-binaries-linux
        - name: windows
          task: build-binaries-windows
        - name: osx
          task: build-binaries-darwin
        - name: osx-m1
          task: build-binaries-darwin-arm64
        - name: system/390
          task: build-binaries-s390x
        - name: arm
          task: build-binaries-arm64
        - name: powerpc
          task: build-binaries-ppc64le
    name: build binaries for ${{ matrix.platform.name }}
    steps:
    - name: Harden Runner
      uses: step-security/harden-runner@2e205a28d0e1da00c5f53b161f4067b052c61f34
      with:
        egress-policy: audit # TODO: change to 'egress-policy: block' after couple of runs

    - uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b
      with:
        submodules: true

    - name: Fetch git tags
      run: |
        git fetch --prune --unshallow --tags

    - uses: actions/setup-go@268d8c0ca0432bb2cf416faae41297df9d262d7f
      with:
        go-version: 1.19.x

    - name: Export BRANCH variable
      uses: ./.github/actions/setup-branch

    - name: Install tools
      run: make install-ci

    - name: Build binaries
      run: make ${{ matrix.platform.task }}
