name: CIT Crossdock

on:
  push:
    branches: [main]

  pull_request:
    branches: [main]

jobs:
  crossdock:
    runs-on: ubuntu-latest

    steps:
    - name: Harden Runner
      uses: step-security/harden-runner@2e205a28d0e1da00c5f53b161f4067b052c61f34
      with:
        egress-policy: audit # TODO: change to 'egress-policy: block' after couple of runs

    - uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b
      with:
        submodules: true

    - name: Fetch git tags
      run: |
        git fetch --prune --unshallow --tags

    - uses: actions/setup-go@268d8c0ca0432bb2cf416faae41297df9d262d7f
      with:
        go-version: 1.19.x

    - name: Export BRANCH variable
      uses: ./.github/actions/setup-branch

    - name: Install tools
      run: make install-ci

    - uses: docker/setup-qemu-action@8b122486cedac8393e77aa9734c3528886e4a1a8

    - name: Build, test, and publish crossdock image
      run: bash scripts/build-crossdock.sh
      env:
        DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
        QUAY_TOKEN: ${{ secrets.QUAY_TOKEN }}

    - name: Output crossdock logs
      run: make crossdock-logs
      if: ${{ failure() }}
