name: Unit Tests

on:
  push:
    branches: [main]

  pull_request:
    branches: [main]

permissions:  # added using https://github.com/step-security/secure-workflows
  contents: read

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
    - name: Harden Runner
      uses: step-security/harden-runner@2e205a28d0e1da00c5f53b161f4067b052c61f34
      with:
        egress-policy: audit # TODO: change to 'egress-policy: block' after couple of runs

    - uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b

    - uses: actions/setup-go@268d8c0ca0432bb2cf416faae41297df9d262d7f
      with:
        go-version: 1.19.x

    - name: Install tools
      run: make install-ci

    - name: Run unit tests
      run: make test-ci

    - name: Upload coverage to codecov
      uses: codecov/codecov-action@d9f34f8cd5cb3b3eb79b3e4b5dae3a16df499a70
      with:
        file: cover.out
        fail_ci_if_error: true
        verbose: true
