name: Deploy desktop to github page

on:
  push:
    branches: [ "test" ]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '19'
      - name: Generate Release Bundle
        run: ./gradlew packageReleaseMsi

      - uses: actions/upload-artifact@v3
        with:
          name: win.msi
          path: ./desktop/build/compose/binaries/main-release/msi/*.msi

  deploy:
    needs: [ build ]
    runs-on: ubuntu-latest
    steps:
      # 1
      - uses: actions/download-artifact@v3
        with:
          name: win.msi

      - name: Echo download path
        run: echo ${{steps.download.outputs.download-path}}

      - name: Draft Release
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          artifacts: "win.msi"
          token: ${{ secrets.TOKEN }}