name: Deploy desktop to github page

on:
  push:
    branches: [ "test" ]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '19'
      - name: Generate Release Bundle
        run: ./gradlew packageReleaseMsi

      - name: Draft Release
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          artifacts: ./desktop/build/compose/binaries/main-release/msi/*.msi
          token: ${{ secrets.TOKEN }}