name: Security Check

on:
  push:
    branches:
      - '*'

jobs:
  security-check:
    name: Set Up
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - uses: docker/setup-buildx-action@v2
      id: buildx
      with:
        install: true

    - name: Build
      id: build-action-image
      run: |
        docker build .

    - name: Run Trivy vulnerability scanner
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: ${{ steps.build-action-image.outputs.fullname }}
        exit-code: "1"
        ignore-unfixed: true
        severity: "CRITICAL,HIGH"
