name: Security Check

on:
  pull_request:
    branches:
      - '*'

jobs:
  security-check:
    name: Security Check
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Build
      id: build-action-image
      run: |
        git_hash=$(git rev-parse --short "$GITHUB_SHA")
        git_branch=${GITHUB_REF#refs/heads/}
        echo "generated-image=$git_branch:$git_hash" >> $GITHUB_OUTPUT
        docker build -t $git_branch:$git_hash .

    - name: Run Trivy vulnerability scanner
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: ${{ steps.build-action-image.outputs.generated-image }}
        exit-code: "1"
        ignore-unfixed: true
        severity: "CRITICAL,HIGH"
